import SpellbookComponent from './spellbook/spellbook.component';
import CharactersComponent from './spellbook/characters/characters.component';
import NewCharacterComponent from './spellbook/characters/newcharacter.component';
import PreparedComponent from './spellbook/prepared/prepared.component';
import KnownComponent from './spellbook/known/known.component';
import SpellbookSpellListComponent from './spellbook/list/spellbookspelllist.component';
import SpellbookBookComponent from './spellbook/book/spellbookbook.component';
import MainComponent from './main/main.component';
import LicenseComponent from './license/license.component';
import SpellComponent from './spells/spell.component';
import AboutComponent from './about/about.component';

const pagesComponents = angular.module('pages.components', []);
pagesComponents.component('spellbook', SpellbookComponent);
pagesComponents.component('characters', CharactersComponent);
pagesComponents.component('newcharacter', NewCharacterComponent);
pagesComponents.component('prepared', PreparedComponent);
pagesComponents.component('known', KnownComponent);
pagesComponents.component('spellbookSpelllist', SpellbookSpellListComponent);
pagesComponents.component('spellbookBook', SpellbookBookComponent);
pagesComponents.component('main', MainComponent);
pagesComponents.component('license', LicenseComponent);
pagesComponents.component('spell', SpellComponent);
pagesComponents.component('about', AboutComponent);
