language: node_js
node_js:
- node
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  yarn: true
notifications:
  email:
    recipients:
    - owlbeardm@gmail.com
install:
- yarn
- yarn install --force
script:
- yarn test


after_success:
  - export LAST_GIT_TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`) && export LAST_GIT_TAG_VERSION=${LAST_GIT_TAG_VERSION:1}
  - export GIT_TAG_VERSION=$(echo $LAST_GIT_TAG_VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')

before_deploy:
-
- if ! [[ $TRAVIS_TAG ]]; then
    yarn sitemap &&
    yarn build --env.version=$GIT_TAG_VERSION-$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER;
  fi
- if [[ $TRAVIS_TAG ]]; then
    yarn sitemap &&
    yarn build --env.version=${TRAVIS_TAG:1} &&
    cd dist &&
    zip scrollbear.zip -r * &&
    mkdir release &&
    mv scrollbear.zip release/scrollbear.zip &&
    cd ..;
  fi

-: &s3_deploy
    secret_access_key: $AMAZON_S3
    provider: s3
    access_key_id: "AKIATNSKVPXD72674NCL"
    skip_cleanup: true
    wait-until-deployed: true

deploy:
  # release a snapshot for each commit on any branch except master
  - <<: *s3_deploy
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$|^feature\/
    bucket: "dev.scrollbear.com"
    local_dir: "./dist"

# release a version when on master and commit is tagged
  - <<: *s3_deploy
    on:
      tags: true
    upload-dir: release
    bucket: "scrollbear-artifacts"
    local_dir: "./dist/release"
