language: node_js
node_js:
  - "node"
cache:
  yarn: true
notifications:
  email:
    recipients:
      - owlbeardm@gmail.com

install:
  - yarn
script:
  - yarn test

before_deploy:
  - yarn build
deploy:
  - on:
      # all_branches: true
      branch: master
    local_dir: ./dist
    keep_history: true
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    provider: pages
    wait-until-deployed: true
