language: node_js
node_js:
- node
cache:
  yarn: true
notifications:
  email:
    recipients:
    - owlbeardm@gmail.com
install:
- yarn
script:
- yarn test
before_deploy:
- yarn build

deploy:
  - on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
    secret_access_key: $AMAZON_S3
    provider: s3
    access_key_id: "AKIATNSKVPXD72674NCL"
    bucket: "scrollbear-artifacts"
    skip_cleanup: true
    wait-until-deployed: true
    local_dir: "./dist"
    upload-dir: snapshot/${TRAVIS_COMMIT::7}
